# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=170)),
                ('description', models.TextField()),
                ('votecount', models.IntegerField(default=0)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestionsapp.Chatroom')),
                ('downvoters', models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL)),
                ('upvoters', models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
