# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestionsapp', '0002_auto_20160603_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='label',
            field=models.SlugField(default='802ay0Yc261O', unique=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='title',
            field=models.CharField(default='sample', max_length=170),
            preserve_default=False,
        ),
    ]
